### PR TITLE
Lowers reputation requirement to add a video to 15.

### PR DESCRIPTION
**Pull request by steelstyle**
The reputation value of 15 corresponds to a new user with a verified email.

Addresses CaptainFact/captain-fact#42.

### CODE REVIEW

**Comment by Miragide** [comment]
@Betree

**Review by Betree — APPROVED** [review]
Looks good to me! Thanks @steelstyle :tada: 

I've added you to https://github.com/orgs/CaptainFact/teams/contributors/members, you'll be able to push your next commits directly to the main repository. It's more convenient as CI currently doesn't run on forks.

**Comment by Betree** [comment]
@steelstyle BTW if you want to get a free tshirt (or plant a tree) these PRs should count as valid for https://hacktoberfest.digitalocean.com

**Comment by steelstyle** [comment]
Thanks, I will take a look: planting a tree is a good idea.

**Pull request merged**
